export const armesGeneriques: string[] = [
    'Épée longue',
    'Arc court',
    'Dague',
    'Masse',
    'Hache de guerre',
    'Bâton',
    'Baguette magique',
    'Glaive',
    'Épée bâtarde',
    'Arc long',
    'Hache à deux mains',
    'Marteau de guerre',
    'Arbalète légère',
    'Bâton de combat',
    'Sceptre',
    'Pavois',
    'Bouclier',
    'Targe',
    'Cimeterre',
    'Rapière',
    'Hallebarde',
    'Pique',
    'Lance',
    'Trident',
    'Épée à deux mains',
    'Hache légère',
    'Marteau léger',
    'Arc composite',
    'Arbalète lourde',
    'Dague de lancer',
    'Faux',
    'Épée courte',
    'Masse à deux mains',
    'Hache d\'armes',
    'Guisarme',
    'Pistolet',
    'Mousquet',
    'Carabine',
    'Hache de jet',
    'Javelot',
    'Fléau',
    'Couteau de chasse',
    'Hache de lancer',
    'Marteau de jet',
    'Bâton de guerre',
    'Bâton à deux mains',
    'Baguette sacrée',
    'Épée dentelée',
    'Hache à croissant',
    'Marteau à pointes',
    'Marteau enflammé',
    'Épée runique',
    'Hache barbelée',
    'Épée flamboyante',
    'Épée de glace',
    'Hache de foudre',
    'Marteau de pierre',
    'Épée de vent',
    'Hache d\'obsidienne',
    'Marteau de cristal',
    'Épée en acier',
    'Hache en fer',
    'Marteau en bronze',
    'Épée en mithril',
    'Hache en thorium',
    'Marteau en titane',
    'Épée en adamantite',
    'Hache en cobalt',
    'Marteau en élémentium',
    'Épée en saronite',
    'Hache en vrai-argent',
    'Marteau en gangracier',
    'Épée en or',
    'Hache en cuivre',
    'Marteau en plaques',
    'Épée de jade',
    'Hache en os',
    'Marteau en écailles',
    'Épée en tissu',
    'Hache en cuir',
    'Marteau en mailles',
    'Épée en bois',
    'Hache en ambre',
    'Marteau en corne',
    'Épée en ivoire',
    'Hache en corail',
    'Marteau en coquillages',
    'Épée en pierre',
    'Hache en verre',
    'Marteau en gemmes',
    'Épée en plumes',
    'Hache en griffes',
    'Marteau en écailles de dragon',
    'Épée en peau de démon',
    'Hache en gangrebois',
    'Marteau en os de géant',
    'Épée en kyparite',
    'Hache en trillium',
    'Marteau en acier foudroyant',
    'Épée en verre de silice',
    'Hache en pierre runique',
    'Marteau en cristal chantant',
    'Épée en acier de l\'aube',
    'Hache en gangrefer',
    'Marteau en acier ébène',
    'Épée en gangracier énergisé',
    'Hache en pierre d\'âme',
    'Marteau en bois ancestral',
    'Épée en os spirituel',
    'Hache en essence arcanique',
    'Marteau en essence de feu',
    'Épée en essence de glace',
    'Hache en essence de nature',
    'Marteau en essence de l\'ombre',
    'Épée en essence de lumière',
    'Hache en essence de l\'eau',
    'Marteau en essence de terre'
    ];


    export const armuresTorseGeneriques: string[] = [
        'Plastron en cuir',
        'Tunique en cuir',
        'Gilet en cuir',
        'Haubert en cuir',
        'Plastron en mailles',
        'Tunique en mailles',
        'Gilet en mailles',
        'Haubert en mailles',
        'Plastron en plaques',
        'Cuirasse en plaques',
        'Harnois en plaques',
        'Armure en plaques',
        'Robe en tissu',
        'Tunique en tissu',
        'Gilet en tissu',
        'Pourpoint en tissu',
        'Plastron en écailles',
        'Tunique en écailles',
        'Gilet en écailles',
        'Haubert en écailles',
        'Plastron en os',
        'Tunique en os',
        'Gilet en os',
        'Haubert en os',
        'Plastron en corne',
        'Tunique en corne',
        'Gilet en corne',
        'Haubert en corne',
        'Plastron en bois',
        'Tunique en bois',
        'Gilet en bois',
        'Haubert en bois',
        'Plastron en ambre',
        'Tunique en ambre',
        'Gilet en ambre',
        'Haubert en ambre',
        'Plastron en ivoire',
        'Tunique en ivoire',
        'Gilet en ivoire',
        'Haubert en ivoire',
        'Plastron en gangrebois',
        'Tunique en gangrebois',
        'Gilet en gangrebois',
        'Haubert en gangrebois',
        'Plastron en kyparite',
        'Tunique en kyparite',
        'Gilet en kyparite',
        'Haubert en kyparite',
        'Plastron en trillium',
        'Tunique en trillium',
        'Gilet en trillium',
        'Haubert en trillium',
        'Plastron en acier foudroyant',
        'Tunique en acier foudroyant',
        'Gilet en acier foudroyant',
        'Haubert en acier foudroyant',
        'Plastron en verre de silice',
        'Tunique en verre de silice',
        'Gilet en verre de silice',
        'Haubert en verre de silice',
        'Plastron en pierre runique',
        'Tunique en pierre runique',
        'Gilet en pierre runique',
        'Haubert en pierre runique',
        'Plastron en cristal chantant',
        'Tunique en cristal chantant',
        'Gilet en cristal chantant',
        'Haubert en cristal chantant',
        'Plastron en acier de l\'aube',
        'Tunique en acier de l\'aube',
        'Gilet en acier de l\'aube',
        'Haubert en acier de l\'aube',
        'Plastron en gangrefer',
        'Tunique en gangrefer',
        'Gilet en gangrefer',
        'Haubert en gangrefer',
        'Plastron en acier ébène',
        'Tunique en acier ébène',
        'Gilet en acier ébène',
        'Haubert en acier ébène',
        'Plastron en gangracier énergisé',
        'Tunique en gangracier énergisé',
        'Gilet en gangracier énergisé',
        'Haubert en gangracier énergisé',
        'Plastron en pierre d\'âme',
        'Tunique en pierre d\'âme',
        'Gilet en pierre d\'âme',
        'Haubert en pierre d\'âme',
        'Plastron en bois ancestral',
        'Tunique en bois ancestral',
        'Gilet en bois ancestral',
        'Haubert en bois ancestral',
        'Plastron en os spirituel',
        'Tunique en os spirituel',
        'Gilet en os spirituel',
        'Haubert en os spirituel',
        'Plastron en essence arcanique',
        'Tunique en essence arcanique',
        'Gilet en essence arcanique',
        'Haubert en essence arcanique',
        'Plastron en essence de feu',
        'Tunique en essence de feu',
        'Gilet en essence de feu',
        'Haubert en essence de feu',
        'Plastron en essence de glace',
        'Tunique en essence de glace',
        'Gilet en essence de glace',
        'Haubert en essence de glace',
        'Plastron en essence de nature',
        'Tunique en essence de nature',
        'Gilet en essence de nature',
        'Haubert en essence de nature',
        'Plastron en essence de l\'ombre',
        'Tunique en essence de l\'ombre',
        'Gilet en essence de l\'ombre',
        'Haubert en essence de l\'ombre',
        'Plastron en essence de lumière',
        'Tunique en essence de lumière',
        'Gilet en essence de lumière',
        'Haubert en essence de lumière',
        'Plastron en essence de l\'eau',
        'Tunique en essence de l\'eau',
        'Gilet en essence de l\'eau',
        'Haubert en essence de l\'eau',
        'Plastron en essence de terre',
        'Tunique en essence de terre',
        'Gilet en essence de terre',
        'Haubert en essence de terre'
    ];


       
      