export const wowLocations = [
    "Orgrimmar",
    "Undercity",
    "Thunder Bluff",
    "Silvermoon City",
    "Tirisfal Glades",
    "The Barrens",
    "Durotar",
    "Mulgore",
    "Hillsbrad Foothills",
    "Alterac Mountains",
    "Western Plaguelands",
    "Eastern Plaguelands",
    "Stratholme",
    "Scholomance",
    "Sunken Temple",
    "Zul'Gurub",
    "Zul'Aman",
    "Gnomeregan",
    "Ironforge",
    "Stormwind City",
    "Dun Morogh",
    "Elwynn Forest",
    "Westfall",
    "Redridge Mountains",
    "Deadwind Pass",
    "Duskwood",
    "Swamp of Sorrows",
    "The Hinterlands",
    "Loch Modan",
    "Searing Gorge",
    "Burning Steppes",
    "Badlands",
    "Blasted Lands",
    "Tanaris",
    "Silithus",
    "Un'Goro Crater",
    "Felwood",
    "Moonglade",
    "Winterspring",
    "Azshara",
    "Darkshore",
    "Teldrassil",
    "Ashenvale",
    "Thousand Needles",
    "Desolace",
    "Feralas",
    "Stonetalon Mountains",
    "Maraudon",
    "Onyxia's Lair",
    "Blackrock Depths",
    "Blackwing Lair",
    "Molten Core",
    "Dire Maul",
    "The Temple of Ahn'Qiraj",
    "Naxxramas",
    "Blackfathom Deeps",
    "Razorfen Downs",
    "Razorfen Kraul",
    "Scarlet Monastery",
    "Shadowfang Keep",
    "Uldaman",
    "Zul'Farrak",
    "Gadgetzan",
    "Booty Bay",
    "Everlook",
    "Ratchet",
    "Darkmoon Faire",
    "Caverns of Time",
    "The Dark Portal",
    "Ahn'Qiraj",
    "Blackrock Mountain",
    "Blackwing Lair",
    "Dire Maul",
    "Karazhan",
    "Naxxramas",
    "Onyxia's Lair",
    "Sunwell Plateau",
    "Tempest Keep",
    "Zul'Aman",
    "Hellfire Peninsula",
    "Zangarmarsh",
    "Terokkar Forest",
    "Nagrand",
    "Blade's Edge Mountains",
    "Shadowmoon Valley",
    "Netherstorm",
    "Isle of Quel'Danas",
    "Borean Tundra",
    "Howling Fjord",
    "Dragonblight",
    "Grizzly Hills",
    "Zul'Drak",
    "Sholazar Basin",
    "Crystalsong Forest",
    "Icecrown",
    "Storm Peaks",
    "Wintergrasp",
    "Dalaran",
    "The Eye of Eternity",
    "The Obsidian Sanctum",
    "Ulduar",
    "Vault of Archavon",
    "Ahn'kahet: The Old Kingdom",
    "Azjol-Nerub"
  ];
  