export enum ItemCategory {
    WEAPON_1H = "Weapon (1H)",
    WEAPON_2H = "Weapon (2H)",
    WEAPON_RANGED = "Weapon (Ranged)",
    ARMOR_HEAD = "Armor (Head)",
    ARMOR_CHEST = "Armor (Chest)",
    ARMOR_LEGS = "Armor (Legs)",
    ARMOR_FEET = "Armor (Feet)",
    ARMOR_HANDS = "Armor (Hands)",
    ARMOR_SHOULDERS = "Armor (Shoulders)",
    SHIELD = "Shield",
    RING = "Ring",
    NECKLACE = "Necklace",
    TRINKET = "Trinket",
    WAND = "Wand",
    STAFF = "Staff",
    POLEARM = "Polearm",
    BOW = "Bow",
    CROSSBOW = "Crossbow",
    DAGGER = "Dagger",
    AXE = "Axe",
    MACE = "Mace",
    SWORD = "Sword",
    BOOK = "Book",
    TORCH = "Torch",
    LANTERN = "Lantern",
}